services:

  adminer:
    image: adminer
    restart: on-failure
    ports:
      - "${ADMINER_PORT}:8080"

  db:
    image: postgres:18.0-alpine3.21
    restart: on-failure
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

  backend:
    restart: on-failure
    build: ./backend
    env_file:
      - .env.dev
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - ./backend:/app
    ports:
      - "${BACKEND_PORT}:3000"

  frontend:
    restart: on-failure
    build: ./frontend
    env_file:
      - .env.dev
    environment:
      - VITE_API_URL=${VITE_API_SERVER}
    volumes:
      - ./frontend:/app
    ports:
      - "${FRONTEND_PORT}:5143"